// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  advantages: dynamic(() => import("./Advantages")),
  all_services: dynamic(() => import("./AllServices")),
  article: dynamic(() => import("./Article")),
  blog_overview: dynamic(() => import("./BlogOverview")),
  cta: dynamic(() => import("./Cta")),
  faq: dynamic(() => import("./Faq")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  how_it_works: dynamic(() => import("./HowItWorks")),
  services_overview: dynamic(() => import("./ServicesOverview")),
  team: dynamic(() => import("./Team")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_image: dynamic(() => import("./TextImage")),
  text_image_reverse: dynamic(() => import("./TextImageReverse")),
  title: dynamic(() => import("./Title")),
};
